### ISSUE TITLE
Undefined behavior for sign-integer-overflow in FLAC__lpc_restore_signal

### ISSUE THREAD

**Issue by HongyuLong24** [xiph/flac#546]
Hi FLAC team,

During our fuzzer test, we got an overflow here (https://github.com/xiph/flac/blob/master/src/libFLAC/lpc.c#L996); while which is an undefined behavior. Could you please provide a solution if we do want to fuzz this type?  Thanks!

Bug link: https://bugs.chromium.org/p/chromium/issues/detail?id=1415151
Reproducer Testcase: https://clusterfuzz.com/download?testcase_id=5152685996310528

some of the logs from ClusterFuzz:
```
Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-5db6cd715d9c67cb2da10ab00c0ecf4f18c86a45
--
  | ../../third_party/flac/src/libFLAC/lpc.c:996:8: runtime error: signed integer overflow: -1659305404 + -947784577 cannot be represented in type 'FLAC__int32' (aka 'int')
  | ==260650==WARNING: invalid path to external symbolizer!
  | ==260650==WARNING: Failed to use and restart external symbolizer!
  | #0 0x556cabc935e4 in FLAC__lpc_restore_signal lpc.c:0
  | #1 0x556cabc9d715 in read_subframe_lpc_ third_party/flac/src/libFLAC/stream_decoder.c:2858:5
  | #2 0x556cabc9948c in read_subframe_ third_party/flac/src/libFLAC/stream_decoder.c:2634:7
  | #3 0x556cabc9948c in read_frame_ third_party/flac/src/libFLAC/stream_decoder.c:2081:7
  | #4 0x556cabc9648f in FLAC__stream_decoder_process_single stream_decoder.c:0
  | #5 0x556cabb21b02 in media::FlacAudioHandler::CopyTo(media::AudioBus*, unsigned long*) media/audio/flac_audio_handler.cc:88:10
  | #6 0x556cabaf1309 in LLVMFuzzerTestOneInput media/audio/flac_audio_handler_fuzzer.cc:33:12
  | #7 0x556cabb53c97 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) third_party/libFuzzer/src/FuzzerLoop.cpp:556:15
  | #8 0x556cabb4098f in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) third_party/libFuzzer/src/FuzzerDriver.cpp:292:6
  | #9 0x556cabb45ce6 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) third_party/libFuzzer/src/FuzzerDriver.cpp:774:9
  | #10 0x556cabb6aaea in main third_party/libFuzzer/src/FuzzerMain.cpp:19:10
  | #11 0x7f7a15c1e082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
  | #12 0x556cabad9e09 in _start
  |  
  | SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../third_party/flac/src/libFLAC/lpc.c:996:8 in
  | FLAC__lpc_restore_signal: OVERFLOW, i=52, j=3, c=-1, d=947784577, sumo=-2607089981
  | FLAC__lpc_restore_signal: OVERFLOW, i=52, j=4, c=-1, d=1006327137, sumo=-3613417118
  | FLAC__lpc_restore_signal: OVERFLOW, i=52, j=5, c=0, d=-330895714, sumo=-3613417118

Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-5db6cd715d9c67cb2da10ab00c0ecf4f18c86a45
../../third_party/flac/src/libFLAC/lpc.c:996:8: runtime error: signed integer overflow: -1659305404 + -947784577 cannot be represented in type 'FLAC__int32' (aka 'int')
==260650==WARNING: invalid path to external symbolizer!
==260650==WARNING: Failed to use and restart external symbolizer!
    #0 0x556cabc935e4 in FLAC__lpc_restore_signal [lpc.c:0](https://chromium.googlesource.com/chromium/src/+/0a09ab86bd0e95fd8c263a48aec4c1f1b0b87b9b/lpc.c#0)
    #1 0x556cabc9d715 in read_subframe_lpc_ [third_party/flac/src/libFLAC/stream_decoder.c:2858](https://chromium.googlesource.com/chromium/deps/flac/+/689da3a7ed50af7448c3f1961d1791c7c1d9c85c/src/libFLAC/stream_decoder.c#2858):5
    #2 0x556cabc9948c in read_subframe_ [third_party/flac/src/libFLAC/stream_decoder.c:2634](https://chromium.googlesource.com/chromium/deps/flac/+/689da3a7ed50af7448c3f1961d1791c7c1d9c85c/src/libFLAC/stream_decoder.c#2634):7
    #3 0x556cabc9948c in read_frame_ [third_party/flac/src/libFLAC/stream_decoder.c:2081](https://chromium.googlesource.com/chromium/deps/flac/+/689da3a7ed50af7448c3f1961d1791c7c1d9c85c/src/libFLAC/stream_decoder.c#2081):7
    #4 0x556cabc9648f in FLAC__stream_decoder_process_single [stream_decoder.c:0](https://chromium.googlesource.com/chromium/src/+/0a09ab86bd0e95fd8c263a48aec4c1f1b0b87b9b/stream_decoder.c#0)
    #5 0x556cabb21b02 in media::FlacAudioHandler::CopyTo(media::AudioBus*, unsigned long*) [media/audio/flac_audio_handler.cc:88](https://chromium.googlesource.com/chromium/src/+/0a09ab86bd0e95fd8c263a48aec4c1f1b0b87b9b/media/audio/flac_audio_handler.cc#88):10
    #6 0x556cabaf1309 in LLVMFuzzerTestOneInput [media/audio/flac_audio_handler_fuzzer.cc:33](https://chromium.googlesource.com/chromium/src/+/0a09ab86bd0e95fd8c263a48aec4c1f1b0b87b9b/media/audio/flac_audio_handler_fuzzer.cc#33):12
    #7 0x556cabb53c97 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) [third_party/libFuzzer/src/FuzzerLoop.cpp:556](https://chromium.googlesource.com/chromium/llvm-project/compiler-rt/lib/fuzzer/+/debe7d2d1982e540fbd6bd78604bf001753f9e74/FuzzerLoop.cpp#556):15
    #8 0x556cabb4098f in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) [third_party/libFuzzer/src/FuzzerDriver.cpp:292](https://chromium.googlesource.com/chromium/llvm-project/compiler-rt/lib/fuzzer/+/debe7d2d1982e540fbd6bd78604bf001753f9e74/FuzzerDriver.cpp#292):6
    #9 0x556cabb45ce6 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) [third_party/libFuzzer/src/FuzzerDriver.cpp:774](https://chromium.googlesource.com/chromium/llvm-project/compiler-rt/lib/fuzzer/+/debe7d2d1982e540fbd6bd78604bf001753f9e74/FuzzerDriver.cpp#774):9
    #10 0x556cabb6aaea in main [third_party/libFuzzer/src/FuzzerMain.cpp:19](https://chromium.googlesource.com/chromium/llvm-project/compiler-rt/lib/fuzzer/+/debe7d2d1982e540fbd6bd78604bf001753f9e74/FuzzerMain.cpp#19):10
    #11 0x7f7a15c1e082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308:16
    #12 0x556cabad9e09 in _start
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../../third_party/flac/src/libFLAC/lpc.c:996:8 in
FLAC__lpc_restore_signal: OVERFLOW, i=52, j=3, c=-1, d=947784577, sumo=-2607089981
FLAC__lpc_restore_signal: OVERFLOW, i=52, j=4, c=-1, d=1006327137, sumo=-3613417118
FLAC__lpc_restore_signal: OVERFLOW, i=52, j=5, c=0, d=-330895714, sumo=-3613417118
```

**Comment by ktmf01** [comment]
During fuzzing of FLACs decoder modules at oss-fuzz, we set `FUZZING_BUILD_MODE_NO_SANITIZE_SIGNED_INTEGER_OVERFLOW` See also:

https://github.com/xiph/flac/blob/3f1f82c8fad729bcaa9dc6eec97a518b375bac0e/src/libFLAC/lpc.c#L967-L974

I consider this overflow completely harmless, resolving it would severely hamper FLACs decoder performance. However, I did not consider other projects also fuzzing FLAC at oss-fuzz.

Maybe I should replace 

 ```
#ifdef FUZZING_BUILD_MODE_NO_SANITIZE_SIGNED_INTEGER_OVERFLOW
```

with

```
#if defined(FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION) && !defined(FUZZING_BUILD_MODE_FULL_SANITIZE_SIGNED_INTEGER_OVERFLOW)
```

so signed integer overflow checking is disabled by default, for other projects than libFLAC itself?

**Comment by HongyuLong24** [comment]
Thanks for the recommendation. It's fine for us to keep the current flag. Feel free to close the issue.
